import = [
  "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 2
padding.y = 1

decorations = "Buttonless"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
size = 12
